---

- hosts: "{{ hosts_group }}"
  remote_user: robin
  vars:
    name1: robin
    hosts_group: "gcp.lhh.pub"
    date1: 2020-02-02
    age1: 21
    age2: '21'

  tasks:
    - name: list files below folder4
      shell: ls  /apps/ansible-test/folder4/|grep -v bak
      register: files_list
      ignore_errors: yes      
     
    - name: print the files_list
      debug:
        msg: "files_list is {{ files_list.stdout_lines  }}"

    - name: cp files below folder4 to bak1
      copy:
        src:  "/apps/ansible-test/folder4/{{ item }}"
        dest: "/apps/ansible-test/folder4/bak1/"
        remote_src: true
      with_items:
        - "{{ files_list.stdout_lines  }}"

    - name: remove the files below folder
      file:
        path: "/apps/ansible-test/folder4/{{ item }}"
        state: absent
      with_items:
        - "{{ files_list.stdout_lines  }}"
