---

- hosts: "{{ hosts_group }}"
  remote_user: robin
  vars:
    hosts_group: ''
    name1: ''
    age1: ''

  tasks:
    - name: show the name1
      debug: 
        msg: "{{ name1 }}"

    - name: show the age1
      debug:
        msg: "{{ age1 }}"

