---

- hosts: "{{ hosts_group }}"
  become: yes
  become_method: sudo
  become_user: javadm
  vars:
    hosts_group: "lhh.pub"
    ansible_ssh_user: robin

  tasks:
    - name: use play default become parameter, run whoami and register to shell_result1
      shell: whoami&&echo $PATH
      register: shell_result1
     
    - name: print the shell_result1
      debug:
        msg: "shell_result1 is {{ shell_result1.stdout_lines  }}"

    - name: rewrite play default become parameter, run whoami and register to shell_result2
      become_user: nodejs
      shell: whoami&&echo $PATH
      register: shell_result2

    - name: print the shell_result2
      debug:
        msg: "shell_result2 is {{ shell_result2.stdout_lines  }}"

    - name: rewrite play default become parameter, run whoami and register to shell_result3
      become: no
      shell: whoami&&echo $PATH
      register: shell_result3

    - name: print the shell_result3
      debug:
        msg: "shell_result3 is {{ shell_result3.stdout_lines  }}"

