---

- hosts: "{{ hosts_group }}"
  become: yes
  become_method: sudo
  become_user: root  

  vars:
    ansible_ssh_user: robin
    name1: root
    hosts_group: "localhost"

  tasks:
    - name: run a shell command1
      shell: "sleep 2;echo 'hello world';sleep 3;echo 'nihao zhongguo';exit 1;sleep 200"
      async: 50
      poll: 0
      register: rst1

    - name: echo rst1 as shell result
      debug:
        msg: "{{ rst1 }}"

    - name: 'get the job and check status'
      async_status: jid={{ rst1.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 50
      ignore_errors: true

    - name: echo the job_result
      debug:
        msg: "{{ job_result }}"

